// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvx2PvPeK8iC2mIjMrZTChBgo8a-84ZBo',
    appId: '1:582591532046:android:d194dbc917129490a3805f',
    messagingSenderId: '582591532046',
    projectId: 'lapor-book-bk-37704',
    storageBucket: 'lapor-book-bk-37704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-d7pyol38AIBb39bi5sue9g4nvlGSSC4',
    appId: '1:582591532046:ios:240edff9b21cfb6fa3805f',
    messagingSenderId: '582591532046',
    projectId: 'lapor-book-bk-37704',
    storageBucket: 'lapor-book-bk-37704.appspot.com',
    iosBundleId: 'com.example.laporBookBk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-d7pyol38AIBb39bi5sue9g4nvlGSSC4',
    appId: '1:582591532046:ios:9e9cb6e9439e961ca3805f',
    messagingSenderId: '582591532046',
    projectId: 'lapor-book-bk-37704',
    storageBucket: 'lapor-book-bk-37704.appspot.com',
    iosBundleId: 'com.example.laporBookBk.RunnerTests',
  );
}
